# Database configuration
#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/your_database_name
#    username: root
#    password: 123456
#    driver-class-name: org.postgresql.Driver

# JPA and Hibernate configuration
#spring:
#  jpa:
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    generate-ddl: true
#    show-sql: true
#
# Hibernate ddl-auto configuration
#spring:
#  jpa:
#    hibernate:
#      ddl-auto: update
